### PR TITLE
ReleaseRecordedEventsMiddleware return the value for the next middlew…

### PR DESCRIPTION
**Pull request by pablonunez**
Return the value for the next middleware configured in the bus.

### CODE REVIEW

**Comment by borNfreee** [comment]
Thank you @pablonunez for the contribution.
According to Tactician's interfaces, this is a good addition. But just out of curiosity - what is your use case? I think using return values with `commands` is more like anti-pattern, isn't it?

**Comment by pablonunez** [comment]
Hi @borNfreee,
We are using league/tactician-bundle in our protect, and some use-cases are synchronous, and others are asynchronous. 

For example to create a user, it's very useful to get the user uuid, and run asynchronous other events. For symfony I think this bundle is good solution. It's less complex that manage all commands asynchronous...

In any case, I think users can choose if use the result or not... :-)

**Comment by pablonunez** [comment]
Could you please tag a minor version with this addition? It's so much better than manage a fork...

**Comment by pablonunez** [comment]
Upps!, It's done. Thanks very much.

**Comment by borNfreee** [comment]
No problem if it helps you :)

But if you are speaking about UUID, then return value is not what you need. Consider the following example:

```php
// Inside UserController.php
...
public function createUserAction(Request $request)
{
    $uuid = $request->get('uuid'); // for simplicity. In real app it would be Symfony Forms
    $name = '...';
    $password = '...';

    $this->get('command_bus')->handle(new CreateUser($uuid, $name, $password);

    return $this->redirect('some_route', $uuid); // here you already know UUID of the user. No need to use return value
}
...
```

**Comment by pablonunez** [comment]
We create the uuid in the handler (Application level)...because I think it's better than give this responsability to the Web/Rest/Console Controller (UI level).
But I have read differents opinions...

**Comment by borNfreee** [comment]
Yes, there are multiple opinions. 

But at this time, when we have rich client side applications, it's ok when JS generates (and immediately uses) UUID and sends it to the server. JS side don't need to wait a response in order to retrieve the entity ID. It's already here. Just one of the many solutions.

**Comment by pablonunez** [comment]
Yes. If you need the uuid in the client side it's a better solution to create via JS. But if you have a REST Api and/or some console commands to create users, it very good if you create the uuid in the handle too.
(We have lot chats about this in the office, hehehe)

**Pull request merged**
